openapi: 3.2.0
info:
  title: LLM-ready Estimates API
  version: 0.1.0
  description: S&P Global Market Intelligence kFinance dataset via LLM-Ready API
servers:
- url: https://kfinance.kensho.com
tags:
- name: Estimates
paths:
  /api/v1/estimates/:
    post:
      operationId: Get Estimates
      description: Get the consensus estimates or guidance for a given company.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EstimatesRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EstimatesRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EstimatesRequest'
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstimatesResponse'
              examples:
                ConsensusEstimatesQuarterlyExample:
                  value:
                    results:
                      '24937':
                        estimate_type: consensus
                        currency: USD
                        period_type: quarterly
                        periods:
                          FY2025Q4:
                            period_end_date: '2025-12-31'
                            estimates:
                            - name: Revenue Consensus High
                              value: '3955000000.000000'
                            - name: Revenue Consensus Low
                              value: '3806400000.000000'
                            - name: Revenue Consensus Mean
                              value: '3881725460.000000'
                            - name: Revenue Consensus Median
                              value: '3883000000.000000'
                    errors: {}
                  summary: '24937'
          description: Indicates a successful request.
        '400':
          description: Indicates that the input parameters are invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Estimates
      summary: Get estimates
      x-summary-source: derived
  /api/v1/estimates/analyst_recommendations/{company_id}:
    get:
      operationId: Get Analyst Recommendations
      description: 'Get analyst recommendations for a given company_id.


        Returns counts of analyst recommendations by rating category and an aggregate analyst consensus score. S&P Global Market Intelligence

        standardizes ratings across brokers on a 5-point scale: 1 = Buy, 2 = Outperform, 3 = Hold, 4 = Underperform, 5 = Sell.

        If an analyst does not provide a recommendation, S&P Global assigns a rating of ''No Opinion''.'
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystRecommendationsResponse'
              examples:
                ConsensusTargetPriceExample:
                  value:
                    results:
                      '24937':
                        effective_date: '2026-03-03'
                        estimates:
                        - name: Consensus Recommendation
                          value: '1.936170'
                        - name: '# of Analysts No Opinion Recommendation - (In-Consensus)'
                          value: '2.000000'
                        - name: '# of Analysts Buy Recommendation - (In-Consensus)'
                          value: '24.000000'
                        - name: '# of Analysts Sell Recommendation - (In-Consensus)'
                          value: '1.000000'
                        - name: '# of Analysts Hold Recommendation - (In-Consensus)'
                          value: '16.000000'
                        - name: '# of Analysts Outperform Recommendation - (In-Consensus)'
                          value: '5.000000'
                        - name: '# of Analysts Underperform Recommendation - (In-Consensus)'
                          value: '1.000000'
                    errors: {}
                  summary: '24937'
          description: Indicates a successful request.
        '400':
          description: Indicates that the input parameters are invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Estimates
      summary: Get analyst recommendations
      x-summary-source: derived
  /api/v1/estimates/consensus_target_price/{company_id}:
    get:
      operationId: Get Consensus Target Price
      description: Get the consensus target price estimates for a given company_id.
      parameters:
      - in: path
        name: company_id
        schema:
          type: integer
        required: true
      security:
      - cookieAuth: []
      - Kensho_JWT_Auth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsensusTargetPriceResponse'
              examples:
                ConsensusTargetPriceExample:
                  value:
                    results:
                      '24937':
                        currency: USD
                        effective_date: '2026-03-03'
                        estimates:
                        - name: Target Price Consensus Mean
                          value: '293.289020'
                        - name: Target Price Consensus Median
                          value: '300.000000'
                        - name: Target Price Consensus High
                          value: '350.000000'
                        - name: Target Price Consensus Low
                          value: '205.000000'
                        - name: 'Target Price - # of Estimates'
                          value: '41.000000'
                        - name: Target Price - Standard Deviation
                          value: '32.468260'
                    errors: {}
                  summary: '24937'
          description: Indicates a successful request.
        '400':
          description: Indicates that the input parameters are invalid.
        '403':
          description: Indicates that the authorization information is missing or invalid.
      tags:
      - Estimates
      summary: Get consensus target price
      x-summary-source: derived
components:
  schemas:
    EstimatesRequestPeriodTypeEnum:
      enum:
      - annual
      - quarterly
      - semi_annual
      type: string
      description: '* `annual` - annual

        * `quarterly` - quarterly

        * `semi_annual` - semi_annual'
    ConsensusTargetPriceItem:
      type: object
      properties:
        name:
          type: string
        value:
          type:
          - string
          - 'null'
          format: decimal
          pattern: ^-?\d{0,22}(?:\.\d{0,6})?$
      required:
      - name
      - value
    NullEnum:
      enum:
      - null
    FiscalStartQuarterEnum:
      enum:
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: '* `1` - 1

        * `2` - 2

        * `3` - 3

        * `4` - 4'
    ConsensusTargetPriceResponse:
      type: object
      properties:
        results:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ConsensusTargetPrice'
        errors:
          type: object
          additionalProperties:
            type: string
            title: error
      required:
      - errors
      - results
    EstimatesPeriod:
      type: object
      properties:
        period_end_date:
          type: string
          format: date
        estimates:
          type: array
          items:
            $ref: '#/components/schemas/EstimatesLineItem'
      required:
      - estimates
      - period_end_date
    AnalystRecommendationsResponse:
      type: object
      properties:
        results:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AnalystRecommendations'
        errors:
          type: object
          additionalProperties:
            type: string
            title: error
      required:
      - errors
      - results
    ConsensusTargetPrice:
      type: object
      properties:
        currency:
          type:
          - string
          - 'null'
        effective_date:
          type:
          - string
          - 'null'
          format: date
        estimates:
          type: array
          items:
            $ref: '#/components/schemas/ConsensusTargetPriceItem'
      required:
      - currency
      - effective_date
      - estimates
    EstimateTypeEnum:
      enum:
      - consensus
      - guidance
      type: string
      description: '* `consensus` - consensus

        * `guidance` - guidance'
    AnalystRecommendationsItem:
      type: object
      properties:
        name:
          type: string
        value:
          type:
          - string
          - 'null'
          format: decimal
          pattern: ^-?\d{0,22}(?:\.\d{0,6})?$
      required:
      - name
      - value
    EstimatesItemResponse:
      type: object
      properties:
        estimate_type:
          $ref: '#/components/schemas/EstimateTypeEnum'
        currency:
          type:
          - string
          - 'null'
        period_type:
          type:
          - string
          - 'null'
        periods:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/EstimatesPeriod'
      required:
      - currency
      - period_type
      - periods
    AnalystRecommendations:
      type: object
      properties:
        effective_date:
          type:
          - string
          - 'null'
          format: date
        estimates:
          type: array
          items:
            $ref: '#/components/schemas/AnalystRecommendationsItem'
      required:
      - effective_date
      - estimates
    FiscalEndQuarterEnum:
      enum:
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: '* `1` - 1

        * `2` - 2

        * `3` - 3

        * `4` - 4'
    EstimatesLineItem:
      type: object
      properties:
        name:
          type: string
        value:
          type:
          - string
          - 'null'
          format: decimal
          pattern: ^-?\d{0,22}(?:\.\d{0,6})?$
      required:
      - name
      - value
    EstimatesResponse:
      type: object
      properties:
        results:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/EstimatesItemResponse'
        errors:
          type: object
          additionalProperties:
            type: string
            title: error
      required:
      - errors
      - results
    EstimatesRequest:
      type: object
      description: Request fields for get_estimates
      properties:
        company_id:
          type: integer
        estimate_type:
          default: consensus
          oneOf:
          - $ref: '#/components/schemas/EstimateTypeEnum'
          - $ref: '#/components/schemas/NullEnum'
        period_type:
          default: quarterly
          oneOf:
          - $ref: '#/components/schemas/EstimatesRequestPeriodTypeEnum'
          - $ref: '#/components/schemas/NullEnum'
        fiscal_start_year:
          type:
          - integer
          - 'null'
          maximum: 9999
          minimum: 1000
        fiscal_end_year:
          type:
          - integer
          - 'null'
          maximum: 9999
          minimum: 1000
        fiscal_start_quarter:
          oneOf:
          - $ref: '#/components/schemas/FiscalStartQuarterEnum'
          - $ref: '#/components/schemas/NullEnum'
        fiscal_end_quarter:
          oneOf:
          - $ref: '#/components/schemas/FiscalEndQuarterEnum'
          - $ref: '#/components/schemas/NullEnum'
        num_periods_forward:
          type:
          - integer
          - 'null'
          maximum: 99
          minimum: 0
        num_periods_backward:
          type:
          - integer
          - 'null'
          maximum: 99
          minimum: 0
      required:
      - company_id
  securitySchemes:
    Kensho_JWT_Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
